/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.example.jsonc --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 875b3aa353877f57626930e1a40c9b0b)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	AE: AnalyticsEngineDataset;
	INGEST_QUEUE: Queue;
	RATE_LIMITER: RateLimit;
	AI: Ai;
	ASSETS: Fetcher;
	RAW_RETENTION_DAYS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RAW_RETENTION_DAYS">> {}
}
